version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: swift-cart-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: swift-cart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # uygulama bağlantısı
      - "15672:15672"  # yönetim paneli (localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
#  app:
#    build: .

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
