spring:
  application:
    name: SwiftCart

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/swift-cart}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    config:
      entryTtl: 60
      countryNames:
        entryTtl: 30
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${YOUR_EMAIL_ADDRESS}
    password: ${YOUR_EMAIL_APP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: info
    org:
      springframework:
        security: Trace
      hibernate: warn
server:
  port: 8082
app:
  base:
    url: http://localhost:8081

jwt:
  access-secret: ${JWT_SECRET_KEY:Axq5ZKcgIlGYMi5lpRWHe5tsebqmy0bL4np2uTDdvvg}
  refresh-secret: ${JWT_REFRESH_KEY:Axq5ZKcgIlGYM5asdaRWHeSsay0SADSADSAvg}
  access-expiration: 900000
  refresh-expiration: 604800000

rate:
  limiter:
    max:
      requests: 5
    time:
      window:
        seconds:60

kind: Application









